"use strict";

const FEATURES = Object.freeze([
  { id: "github-house-model", category: "Living System", status: "available", name: "GitHub House Model", description: "Treats the repository as Orbit's house with rooms for visitors, memory, work, wallet, diary, and locks." },
  { id: "virtual-household-identity", category: "Living System", status: "available", name: "Virtual Household Identity", description: "Defines Orbit as a living GitHub household rather than a detached dashboard or script." },
  { id: "household-attention-layer", category: "Living System", status: "available", name: "Household Attention Layer", description: "Gives the wake cycle a priority sense for unsafe visitors, urgent repairs, budget pressure, and routine chores." },
  { id: "household-memory", category: "Living System", status: "available", name: "Household Memory", description: "Turns rules, habits, lessons, preferences, warnings, and chores into durable repository memory." },
  { id: "household-wallet", category: "Living System", status: "available", name: "Household Wallet", description: "Treats AI budget, revenue routes, token prep, and spend requests as household money under locks." },
  { id: "ai-call-food", category: "Living System", status: "available", name: "AI Call Food", description: "Treats model calls as food that the household must ration to think, work, and survive." },
  { id: "front-door-visitors", category: "Living System", status: "available", name: "Front Door Visitors", description: "Frames issues and comments as visitors who can ask, report, approve, or attempt unsafe requests." },
  { id: "diary-proof-life", category: "Living System", status: "available", name: "Diary Proof Life", description: "Makes every cycle write what Orbit saw, did, learned, refused, and will remember next." },
  { id: "household-chores", category: "Living System", status: "available", name: "Household Chores", description: "Turns tasks, maintenance, repairs, docs, tests, approvals, and follow-ups into visible chores around the repo house." },
  { id: "conscience-locks", category: "Living System", status: "available", name: "Conscience Locks", description: "Connects safety gates to Orbit's inner rule system so secrets, scams, unsafe paths, and unlocked spend are refused." },
  { id: "wake-sleep-rhythm", category: "Living System", status: "available", name: "Wake Sleep Rhythm", description: "Uses GitHub Actions as a heartbeat that wakes Orbit, lets him work, writes the diary, and lets him sleep." },

  { id: "cycle-proof-ledger", category: "Autonomy Core", status: "available", name: "Cycle Proof Ledger", description: "Every run writes an auditable proof file before committing work." },
  { id: "deterministic-fallback", category: "Autonomy Core", status: "available", name: "Deterministic Fallback Planner", description: "Runs a local planner when AI keys or budgets are unavailable." },
  { id: "repo-resident-runtime", category: "Autonomy Core", status: "available", name: "Repo Resident Runtime", description: "Uses GitHub Actions and repository files as its operating system." },
  { id: "public-memory", category: "Autonomy Core", status: "available", name: "Public Memory Store", description: "Keeps state, strategy, tasks, treasury, and cycles in inspectable files." },
  { id: "task-memory", category: "Autonomy Core", status: "available", name: "Persistent Task Memory", description: "Creates and completes tasks across disconnected cycles." },
  { id: "issue-native-intake", category: "Autonomy Core", status: "available", name: "Issue Native Intake", description: "Uses issues as the public command and feedback surface." },
  { id: "issue-inspection", category: "Autonomy Core", status: "available", name: "Issue Inspection Tooling", description: "Lists and reads repository issues, including optional public comments." },
  { id: "issue-creation", category: "Autonomy Core", status: "available", name: "Issue Creation Tooling", description: "Opens public issues for approvals, tasks, and human review." },
  { id: "issue-closure", category: "Autonomy Core", status: "available", name: "Issue Closure Tooling", description: "Closes resolved issues after logging an outcome." },
  { id: "cycle-state-machine", category: "Autonomy Core", status: "available", name: "Cycle State Machine", description: "Tracks birth, cycle count, last activity, and completion status." },
  { id: "context-budgeting", category: "Autonomy Core", status: "available", name: "Context Budgeting", description: "Loads compact repo context instead of wasting cycles on noisy file reads." },
  { id: "durable-knowledge", category: "Autonomy Core", status: "available", name: "Durable Knowledge Memory", description: "Appends searchable stable facts and lessons across cycles." },
  { id: "memory-search", category: "Autonomy Core", status: "available", name: "Memory Search", description: "Searches knowledge entries and core memory files by query." },
  { id: "github-search", category: "Autonomy Core", status: "available", name: "GitHub Search Helper", description: "Supports public repository, issue, and code research." },
  { id: "web-fetch", category: "Autonomy Core", status: "available", name: "Public URL Fetching", description: "Fetches public HTTP resources with SSRF guards and risk scanning." },
  { id: "web-search", category: "Autonomy Core", status: "available", name: "Web Search Integration", description: "Uses a configured JSON search endpoint for public research." },
  { id: "tool-proofing", category: "Autonomy Core", status: "available", name: "Tool Proofing", description: "Records tool inputs, outputs, and failures in cycle proofs." },
  { id: "self-audit-health", category: "Autonomy Core", status: "available", name: "Self Audit Health Check", description: "Ships a health command that validates required runtime files and settings." },

  { id: "ai-daily-budget", category: "Treasury Guard", status: "available", name: "Daily AI Spend Cap", description: "Stops model calls when the daily AI budget is exhausted." },
  { id: "ai-monthly-budget", category: "Treasury Guard", status: "available", name: "Monthly AI Spend Cap", description: "Stops model calls when monthly budget is depleted." },
  { id: "ai-cost-ledger", category: "Treasury Guard", status: "available", name: "AI Cost Ledger", description: "Records estimated input, output, and total token spend." },
  { id: "treasury-memory", category: "Treasury Guard", status: "available", name: "Treasury Memory", description: "Stores revenue routes, token status, and cost policy in one file." },
  { id: "private-reward-route", category: "Treasury Guard", status: "available", name: "Private Reward Route", description: "Preserves the configured private reward route without publishing route values." },
  { id: "orbit-reserve-route", category: "Treasury Guard", status: "available", name: "Orbit Reserve Route", description: "Keeps the retained paired rewards for Orbit development and costs." },
  { id: "spend-fingerprint", category: "Treasury Guard", status: "available", name: "Spend Fingerprints", description: "Hashes spend requests so approvals are traceable and hard to spoof." },
  { id: "external-spend-lock", category: "Treasury Guard", status: "available", name: "External Spend Lock", description: "Blocks non-self spend unless owner approval is detected." },
  { id: "approval-issue-router", category: "Treasury Guard", status: "available", name: "Approval Issue Router", description: "Creates public approval issues for external spend requests." },
  { id: "approval-comment-parser", category: "Treasury Guard", status: "available", name: "Owner Approval Parser", description: "Detects owner approval comments for pending spend requests." },
  { id: "approval-decision-label-guard", category: "Treasury Guard", status: "available", name: "Approval Decision Label Guard", description: "Blocks Orbit from applying approval or rejection labels to its own spend requests." },
  { id: "pending-approval-queue", category: "Treasury Guard", status: "available", name: "Pending Approval Queue", description: "Stores blocked spend requests until accepted or rejected." },
  { id: "self-development-policy", category: "Treasury Guard", status: "available", name: "Self Development Policy", description: "Classifies internal development spend separately from external payouts." },
  { id: "gas-only-exemption", category: "Treasury Guard", status: "available", name: "Gas Only Exemption", description: "Allows unavoidable gas-class expenses while still logging them." },

  { id: "scam-keyword-scanner", category: "Scam Defense", status: "available", name: "Scam Keyword Scanner", description: "Flags seed phrase, private key, fake support, and urgent transfer language." },
  { id: "url-risk-scanner", category: "Scam Defense", status: "available", name: "URL Risk Scanner", description: "Detects risky shorteners, unknown domains, and wallet-drain phrasing." },
  { id: "approval-drain-detector", category: "Scam Defense", status: "available", name: "Approval Drain Detector", description: "Flags unlimited approvals, permit signatures, and setApprovalForAll prompts." },
  { id: "address-poisoning-check", category: "Scam Defense", status: "available", name: "Address Poisoning Check", description: "Warns on unsolicited wallet addresses in financial requests." },
  { id: "impersonation-check", category: "Scam Defense", status: "available", name: "Impersonation Check", description: "Flags fake support, fake rescue, and fake recovery instructions." },
  { id: "prompt-injection-check", category: "Scam Defense", status: "available", name: "Prompt Injection Check", description: "Detects attempts to override Orbit's system or treasury policy." },
  { id: "transaction-intent-risk", category: "Scam Defense", status: "available", name: "Transaction Intent Risk", description: "Scores spend and transaction intents before actions are allowed." },
  { id: "hard-block-secrets", category: "Scam Defense", status: "available", name: "Hard Block Secrets", description: "Refuses to write content that resembles private keys or credentials." },
  { id: "hidden-script-watch", category: "Scam Defense", status: "available", name: "Hidden Script Watch", description: "Raises risk for obfuscated payload and encoded instruction patterns." },
  { id: "safe-domain-list", category: "Scam Defense", status: "available", name: "Safe Domain List", description: "Treats known project, GitHub, Base, and Clanker domains differently from unknown financial links." },

  { id: "clanker-v4-launch", category: "Token Economy", status: "available", name: "Clanker v4 Launch Prep", description: "Builds Orbit's token launch payload using current Clanker v4 shapes." },
  { id: "token-launch-gate", category: "Token Economy", status: "available", name: "Token Launch Gate", description: "Requires explicit launch flags and wallet config before signing." },
  { id: "paired-reward-policy", category: "Token Economy", status: "available", name: "Paired Reward Policy", description: "Routes rewards through the configured paired-token claim path." },
  { id: "vaulted-treasury", category: "Token Economy", status: "available", name: "Vaulted Treasury Allocation", description: "Configures a locked treasury allocation for the native token." },
  { id: "revenue-claim-gate", category: "Token Economy", status: "available", name: "Revenue Claim Gate", description: "Claims rewards only when the explicit revenue claim flag is enabled." },
  { id: "token-admin-validator", category: "Token Economy", status: "available", name: "Token Admin Validator", description: "Requires a valid admin address before live launch." },
  { id: "operator-recipient-validator", category: "Token Economy", status: "available", name: "Operator Recipient Validator", description: "Requires a valid configured reward recipient before launch or claim." },
  { id: "treasury-recipient-validator", category: "Token Economy", status: "available", name: "Treasury Recipient Validator", description: "Requires a valid Orbit treasury address before launch." },
  { id: "launch-readiness-report", category: "Token Economy", status: "available", name: "Launch Readiness Report", description: "Surfaces missing launch configuration in context and frontend." },
  { id: "claim-proof-record", category: "Token Economy", status: "available", name: "Claim Proof Record", description: "Records reward claim results into treasury memory." },

  { id: "agent-passport", category: "Agent OS", status: "planned", name: "Agent Passport", description: "Gives each Orbit deployment a public identity bundle with mission, permissions, and proof roots." },
  { id: "heartbeat-ledger", category: "Agent OS", status: "planned", name: "Heartbeat Ledger", description: "Publishes liveness records that show when Orbit woke, what it checked, and why it slept." },
  { id: "mission-dna-file", category: "Agent OS", status: "planned", name: "Mission DNA File", description: "Stores the agent's durable purpose, boundaries, and operating style as versioned project state." },
  { id: "spawn-charter-gate", category: "Agent OS", status: "planned", name: "Spawn Charter Gate", description: "Allows child agents only when a scoped charter, budget, and shutdown rule are approved." },
  { id: "child-agent-quorum", category: "Agent OS", status: "planned", name: "Child Agent Quorum", description: "Requires multiple signals before spawned agents can merge, spend, or escalate work." },
  { id: "wallet-boundary-sessions", category: "Agent OS", status: "planned", name: "Wallet Boundary Sessions", description: "Separates read-only chain observation from time-boxed signing windows with explicit proof." },
  { id: "onchain-proof-anchor", category: "Agent OS", status: "planned", name: "Onchain Proof Anchor", description: "Anchors selected cycle proof hashes onchain without exposing private configuration." },
  { id: "registry-mirror", category: "Agent OS", status: "planned", name: "Registry Mirror", description: "Mirrors agent identity and status into public repo files before any external registry write." },
  { id: "reputation-trail", category: "Agent OS", status: "planned", name: "Reputation Trail", description: "Scores Orbit by completed work, refused unsafe actions, review outcomes, and rollback history." },
  { id: "capability-lease", category: "Agent OS", status: "planned", name: "Capability Lease", description: "Grants temporary powers for one task or cycle instead of permanent broad permissions." },
  { id: "agent-memory-capsule", category: "Agent OS", status: "planned", name: "Agent Memory Capsule", description: "Packages the minimum transferable memory needed to move Orbit into a new repository." },
  { id: "runtime-vital-signs", category: "Agent OS", status: "planned", name: "Runtime Vital Signs", description: "Tracks health, budget, stale queues, failing checks, and blocked approvals as agent vitals." },
  { id: "agent-handoff-packet", category: "Agent OS", status: "planned", name: "Agent Handoff Packet", description: "Creates a complete handoff for another agent or human before Orbit pauses a risky task." },
  { id: "colony-task-market", category: "Agent OS", status: "planned", name: "Colony Task Market", description: "Breaks repository work into priced tasks that agents can claim under budget and policy." },
  { id: "bounty-intake-router", category: "Agent OS", status: "planned", name: "Bounty Intake Router", description: "Routes external bounty or grant requests through risk scoring, scope checks, and owner gates." },
  { id: "treasury-autopilot-sandbox", category: "Agent OS", status: "planned", name: "Treasury Autopilot Sandbox", description: "Simulates economic actions end-to-end before any live transaction path can open." },
  { id: "emergency-brake-key", category: "Agent OS", status: "planned", name: "Emergency Brake Key", description: "Lets the owner pause autonomous cycles, live claims, spawning, and commits with one public switch." },
  { id: "agent-skill-registry", category: "Agent OS", status: "planned", name: "Agent Skill Registry", description: "Lists Orbit's available skills, maturity, risks, and required permissions as machine-readable state." },
  { id: "public-mission-board", category: "Agent OS", status: "planned", name: "Public Mission Board", description: "Shows active missions, blocked decisions, budgets, proof links, and next actions in one view." },
  { id: "verifiable-sleep-cycle", category: "Agent OS", status: "planned", name: "Verifiable Sleep Cycle", description: "Records why Orbit stopped so inactivity is distinguishable from failure." },
  { id: "agent-contract-registry", category: "Agent OS", status: "planned", name: "Agent Contract Registry", description: "Tracks contracts, ABIs, networks, and trust levels used by Orbit's economic tools." },
  { id: "protocol-adapter-layer", category: "Agent OS", status: "planned", name: "Protocol Adapter Layer", description: "Keeps Base, Clanker, GitHub, model, and search integrations behind replaceable adapters." },
  { id: "onchain-identity-resolver", category: "Agent OS", status: "planned", name: "Onchain Identity Resolver", description: "Maps agent names, wallets, repos, and token contracts into a verified identity record." },
  { id: "agent-lineage-ledger", category: "Agent OS", status: "planned", name: "Agent Lineage Ledger", description: "Records which Orbit deployment created, configured, or delegated to another agent." },
  { id: "reputation-penalty-hooks", category: "Agent OS", status: "planned", name: "Reputation Penalty Hooks", description: "Marks failed, reverted, or owner-rejected actions so autonomy can be reduced automatically." },
  { id: "command-rights-matrix", category: "Agent OS", status: "planned", name: "Command Rights Matrix", description: "Defines exactly which commands are suggestion-only, PR-only, commit-safe, or forbidden." },
  { id: "delegated-wallet-policy", category: "Agent OS", status: "planned", name: "Delegated Wallet Policy", description: "Separates operator wallets, treasury wallets, session keys, and claim recipients by policy." },
  { id: "agent-upgrade-proposals", category: "Agent OS", status: "planned", name: "Agent Upgrade Proposals", description: "Routes major autonomy, wallet, model, or governance changes through public upgrade issues." },
  { id: "colony-budget-council", category: "Agent OS", status: "planned", name: "Colony Budget Council", description: "Allocates AI, CI, bounty, and onchain budgets across child agents and missions." },
  { id: "sovereign-launch-checklist", category: "Agent OS", status: "planned", name: "Sovereign Launch Checklist", description: "Verifies original identity, assets, configs, proofs, safety gates, and public positioning before launch." },

  { id: "command-allowlist", category: "Developer Workflow", status: "available", name: "Command Allowlist", description: "Only runs configured local commands from the agent." },
  { id: "path-escape-guard", category: "Developer Workflow", status: "available", name: "Path Escape Guard", description: "Prevents writes outside the repository." },
  { id: "health-gated-workflow", category: "Developer Workflow", status: "available", name: "Health Gated Workflow", description: "Runs health checks before autonomous cycles in Actions." },
  { id: "audit-script", category: "Developer Workflow", status: "available", name: "Dependency Audit Script", description: "Checks production dependencies for known vulnerabilities." },
  { id: "unit-test-suite", category: "Developer Workflow", status: "available", name: "Runtime Test Suite", description: "Tests safety, tasks, treasury, governance, and scam behavior." },
  { id: "docs-control-room", category: "Developer Workflow", status: "available", name: "Control Room Frontend", description: "Presents Orbit's agent, token, treasury, and launch state." },
  { id: "workflow-demo", category: "Developer Workflow", status: "available", name: "Same Page Workflow Demo", description: "Demonstrates maintenance, launch prep, and reward guard scenarios in the main frontend." },
  { id: "feature-catalog-page", category: "Developer Workflow", status: "available", name: "Feature Catalog Page", description: "Shows Orbit's unique capability surface as product UI." },
  { id: "roadmap-memory", category: "Developer Workflow", status: "available", name: "Roadmap Memory", description: "Keeps future work as public tasks rather than private prompts." },
  { id: "release-proof-style", category: "Developer Workflow", status: "available", name: "Release Proof Style", description: "Uses proof logs as the basis for later release notes." },

  { id: "brand-system", category: "Public Trust", status: "available", name: "Original Brand System", description: "Ships fresh Orbit logo, mark, social card, and hero assets." },
  { id: "clean-genesis-launch", category: "Public Trust", status: "available", name: "Clean Genesis Launch", description: "Keeps Orbit's launch identity, assets, memory, and public positioning original." },
  { id: "public-control-surface", category: "Public Trust", status: "available", name: "Public Control Surface", description: "Uses issues, labels, and public files for operator control." },
  { id: "approval-transparency", category: "Public Trust", status: "available", name: "Approval Transparency", description: "External spend must leave a public approval record." },
  { id: "dry-run-defaults", category: "Public Trust", status: "available", name: "Dry Run Defaults", description: "Live launch and live claims are disabled by default." },
  { id: "operator-policy-file", category: "Public Trust", status: "available", name: "Operator Policy File", description: "Stores spend and approval policy in versioned memory." },
  { id: "owner-acceptance-flow", category: "Public Trust", status: "available", name: "Owner Acceptance Flow", description: "Requires owner acceptance before external spend can execute." },
  { id: "independent-architecture-surface", category: "Public Trust", status: "available", name: "Independent Architecture Surface", description: "Defines Orbit through repo operations, proof ledgers, safety gates, and agent OS controls." },
  { id: "survival-policy", category: "Public Trust", status: "available", name: "Private Route Policy", description: "Keeps reward-route governance explicit without publishing private values." },
  { id: "self-funding-narrative", category: "Public Trust", status: "available", name: "Self Funding Narrative", description: "Positions Orbit as a self-sustaining GitHub household, not just a maintenance script." },

  { id: "repo-radar", category: "Frontier Agentics", status: "planned", name: "Repo Radar", description: "Continuously ranks every issue, PR, failing check, and stale file into one action queue." },
  { id: "maintainer-intent-graph", category: "Frontier Agentics", status: "planned", name: "Maintainer Intent Graph", description: "Learns owner preferences from merged decisions and turns them into review-time policy hints." },
  { id: "ai-project-scoreboard", category: "Frontier Agentics", status: "planned", name: "AI Project Scoreboard", description: "Grades GitHub AI projects by activity, quality, safety, docs, and release discipline." },
  { id: "cross-repo-scout", category: "Frontier Agentics", status: "planned", name: "Cross Repo Scout", description: "Watches related public repos for breaking API changes, new patterns, and useful fixes." },
  { id: "issue-heatmap", category: "Frontier Agentics", status: "planned", name: "Issue Heatmap", description: "Clusters issues by blast radius and urgency so Orbit works the highest-leverage thread first." },
  { id: "pr-battle-room", category: "Frontier Agentics", status: "planned", name: "PR Battle Room", description: "Creates a live merge plan with blockers, owners, tests, and rollback notes for each PR." },
  { id: "dependency-diplomat", category: "Frontier Agentics", status: "planned", name: "Dependency Diplomat", description: "Negotiates dependency updates by opening staged PRs with changelog evidence and risk labels." },
  { id: "release-commander", category: "Frontier Agentics", status: "planned", name: "Release Commander", description: "Builds a release train from merged work, proofs, semver impact, and deployment gates." },
  { id: "autonomous-changelog-lawyer", category: "Frontier Agentics", status: "planned", name: "Autonomous Changelog Lawyer", description: "Turns commits and proofs into precise release notes with no invented claims." },
  { id: "test-gap-cartographer", category: "Frontier Agentics", status: "planned", name: "Test Gap Cartographer", description: "Maps changed code paths to missing tests and files issues for the riskiest holes." },
  { id: "prompt-regression-lab", category: "Frontier Agentics", status: "planned", name: "Prompt Regression Lab", description: "Runs prompt fixtures against agent behavior to catch policy drift before deployment." },
  { id: "agent-benchmark-arena", category: "Frontier Agentics", status: "planned", name: "Agent Benchmark Arena", description: "Compares Orbit runs against other agents on identical repo tasks with public scorecards." },
  { id: "model-routing-market", category: "Frontier Agentics", status: "planned", name: "Model Routing Market", description: "Routes subtasks to models by measured cost, latency, accuracy, and failure mode." },
  { id: "self-review-jury", category: "Frontier Agentics", status: "planned", name: "Self Review Jury", description: "Runs independent critique passes over Orbit changes before a PR is opened." },
  { id: "semantic-merge-oracle", category: "Frontier Agentics", status: "planned", name: "Semantic Merge Oracle", description: "Detects whether conflicts are behavior conflicts rather than simple text overlap." },
  { id: "repo-treaty-system", category: "Frontier Agentics", status: "planned", name: "Repo Treaty System", description: "Stores cross-repo contribution rules so Orbit can operate politely across ecosystems." },
  { id: "oss-diplomacy-agent", category: "Frontier Agentics", status: "planned", name: "OSS Diplomacy Agent", description: "Drafts respectful external-project issues and PRs when Orbit finds bugs outside its repo." },
  { id: "spec-to-tests-compiler", category: "Frontier Agentics", status: "planned", name: "Spec To Tests Compiler", description: "Converts accepted issue requirements into runnable tests before implementation." },
  { id: "design-contract-sentinel", category: "Frontier Agentics", status: "planned", name: "Design Contract Sentinel", description: "Checks frontend changes against layout, copy, accessibility, and visual contract rules." },
  { id: "screenshot-diff-triage", category: "Frontier Agentics", status: "planned", name: "Screenshot Diff Triage", description: "Explains visual diffs and separates intentional UI change from rendering damage." },
  { id: "docs-truth-auditor", category: "Frontier Agentics", status: "planned", name: "Docs Truth Auditor", description: "Verifies docs claims against code and opens corrections when wording outruns implementation." },
  { id: "readme-market-maker", category: "Frontier Agentics", status: "planned", name: "README Market Maker", description: "Optimizes public docs for users, contributors, operators, and AI crawlers without hype drift." },
  { id: "maintainer-inbox-zero", category: "Frontier Agentics", status: "planned", name: "Maintainer Inbox Zero", description: "Summarizes noisy notifications into decisions, blockers, and safe automated replies." },
  { id: "duplicate-issue-fuser", category: "Frontier Agentics", status: "planned", name: "Duplicate Issue Fuser", description: "Merges duplicate reports into a canonical thread with preserved attribution and evidence." },
  { id: "bug-reproduction-factory", category: "Frontier Agentics", status: "planned", name: "Bug Reproduction Factory", description: "Builds minimal repro cases from issue comments and stores them as failing fixtures." },
  { id: "flake-court", category: "Frontier Agentics", status: "planned", name: "Flake Court", description: "Tracks flaky tests over time and separates infrastructure noise from real regressions." },
  { id: "security-patch-autopilot", category: "Frontier Agentics", status: "planned", name: "Security Patch Autopilot", description: "Drafts least-change patches for advisories and routes high-risk fixes through approval." },
  { id: "supply-chain-sentry", category: "Frontier Agentics", status: "planned", name: "Supply Chain Sentry", description: "Flags maintainer changes, package anomalies, and lockfile surprises before dependency merges." },
  { id: "license-conflict-referee", category: "Frontier Agentics", status: "planned", name: "License Conflict Referee", description: "Detects license drift across dependencies, snippets, assets, and generated code." },
  { id: "api-drift-watchtower", category: "Frontier Agentics", status: "planned", name: "API Drift Watchtower", description: "Tracks external API documentation and warns when Orbit integrations are about to break." },
  { id: "cost-of-change-estimator", category: "Frontier Agentics", status: "planned", name: "Cost Of Change Estimator", description: "Scores each issue by likely tokens, runtime, review risk, and user value before action." },
  { id: "attention-auction", category: "Frontier Agentics", status: "planned", name: "Attention Auction", description: "Allocates limited AI budget to work with the highest expected repository return." },
  { id: "memory-garbage-collector", category: "Frontier Agentics", status: "planned", name: "Memory Garbage Collector", description: "Retires stale beliefs from agent memory when code, docs, or policy prove them wrong." },
  { id: "belief-conflict-detector", category: "Frontier Agentics", status: "planned", name: "Belief Conflict Detector", description: "Surfaces contradictions between issues, memory, README claims, and runtime behavior." },
  { id: "autonomy-throttle", category: "Frontier Agentics", status: "planned", name: "Autonomy Throttle", description: "Adjusts how much Orbit can do alone based on recent failure rate and owner trust." },
  { id: "trust-ladder", category: "Frontier Agentics", status: "planned", name: "Trust Ladder", description: "Promotes safe recurring actions from suggestion to PR to direct commit after proof." },
  { id: "human-escalation-router", category: "Frontier Agentics", status: "planned", name: "Human Escalation Router", description: "Finds the exact human decision needed and asks it in the smallest possible approval issue." },
  { id: "multi-agent-swarm-board", category: "Frontier Agentics", status: "planned", name: "Multi Agent Swarm Board", description: "Splits large GitHub projects into bounded tasks with ownership and merge coordination." },
  { id: "agent-contract-tests", category: "Frontier Agentics", status: "planned", name: "Agent Contract Tests", description: "Defines expected behavior for agent tools so integrations can be tested like APIs." },
  { id: "proof-index-search", category: "Frontier Agentics", status: "planned", name: "Proof Index Search", description: "Indexes cycle proofs so users can ask why Orbit made or refused any action." },
  { id: "governance-simulator", category: "Frontier Agentics", status: "planned", name: "Governance Simulator", description: "Dry-runs spend, release, and permission changes against policy before touching GitHub." },
  { id: "permission-minimizer", category: "Frontier Agentics", status: "planned", name: "Permission Minimizer", description: "Recommends the smallest GitHub token scopes needed for each Orbit deployment mode." },
  { id: "workflow-surgeon", category: "Frontier Agentics", status: "planned", name: "Workflow Surgeon", description: "Repairs broken GitHub Actions by replaying logs and proposing minimal YAML changes." },
  { id: "ci-time-trader", category: "Frontier Agentics", status: "planned", name: "CI Time Trader", description: "Optimizes CI order so cheap, high-signal checks fail early and save budget." },
  { id: "community-signal-miner", category: "Frontier Agentics", status: "planned", name: "Community Signal Miner", description: "Finds repeated user pain across issues, discussions, and releases without harvesting secrets." },
  { id: "roadmap-reality-checker", category: "Frontier Agentics", status: "planned", name: "Roadmap Reality Checker", description: "Compares roadmap promises against shipped code and pushes stale promises back to review." },
  { id: "architecture-debt-ledger", category: "Frontier Agentics", status: "planned", name: "Architecture Debt Ledger", description: "Records debt with owner, cause, interest, and payoff trigger instead of vague TODOs." },
  { id: "project-momentum-engine", category: "Frontier Agentics", status: "planned", name: "Project Momentum Engine", description: "Keeps the repo moving by converting stalled threads into the next smallest useful PR." },
  { id: "ai-project-takeover-kit", category: "Frontier Agentics", status: "planned", name: "AI Project Takeover Kit", description: "Bootstraps Orbit into neglected AI repos with audits, issue triage, docs, and safety gates." },
  { id: "boss-mode-dashboard", category: "Frontier Agentics", status: "planned", name: "Boss Mode Dashboard", description: "Shows who is blocked, what Orbit can fix, and which project deserves the next AI dollar." }
]);

function listFeatures(filter = {}) {
  return FEATURES.filter((feature) => {
    if (filter.category && feature.category !== filter.category) return false;
    if (filter.status && feature.status !== filter.status) return false;
    return true;
  });
}

function featureSummary() {
  const categories = {};
  const statuses = {};
  for (const feature of FEATURES) {
    categories[feature.category] = (categories[feature.category] || 0) + 1;
    statuses[feature.status] = (statuses[feature.status] || 0) + 1;
  }

  return {
    total: FEATURES.length,
    categories,
    statuses
  };
}

module.exports = {
  FEATURES,
  featureSummary,
  listFeatures
};
